project:
  type: book

book:
  title: "Plot2Publish"
  author: ""
  date: ""
  site-url: https://biobenchtobytes.github.io/P2P
  chapters:
    - index.qmd
    - part: "SESSION 1: Code Context"
      chapters:
        - pages/versioning.qmd
        - pages/environments.qmd
    - part: "SESSION 2: Version Control"
      chapters:
        - pages/git.qmd
        - pages/github.qmd
    - part: "SESSION 3: Collaboration"
      chapters:
        - pages/code-review.qmd
        - pages/issues-branches-prs.qmd
    - part: "SESSION 4: Prepare to Publish!"
      chapters:
        - pages/licensing.qmd
        - pages/releases-dois.qmd
        - pages/razzle-dazzle.qmd
        - pages/data-repositories.qmd
    - part: "Resources"
      chapters:
        - pages/checklist.qmd
        - pages/resources.qmd
        - pages/learning.qmd
  sidebar:
    search: true
    logo: pages/images/logo_transparent.png
    style: docked
    background: dark
  navbar:
    background: dark

format:
  html:
    theme: flatly
    css: theme.css
    number-sections: false

page-footer: |
  Material developed by Bench2Bytes © 2025

bread-crumbs: true
execute:
  freeze: true
knitr:
  opts_chunk:
    python.reticulate: false